---
- hosts: all
  vars_files:
    - vars/main.yml
  become: true
  roles:
    - RHEL7-CIS
    - { role: geerlingguy.firewall }
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: Apache - install latest
    yum: name=httpd state=latest
  - name: SSL - install latest mod_ssl
    yum: name=mod_ssl state=latest
  - name: Create a directory for apache SSL
    command: mkdir -p /etc/httpd/ssl/certs
  - name: create self-signed SSL cert
    command: openssl req -new -nodes -x509 -subj "/C=US/ST=Pennsylvania/L=Philadelphia/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/httpd/ssl/certs/test_site.key -out /etc/httpd/ssl/certs/test_site.crt -extensions v3_ca creates=/etc/httpd/ssl/certs/test_site.crt
  - name: write the vhosts file for apache
    template: src=vhosts.conf dest=/etc/httpd/conf.d/vhosts.conf
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - name: Push the web content (index.html)
    template: 
      src: index.html
      dest: /var/www/html/index.html
      owner: apache
      group: apache
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
